project:
  type: website

website:
  title: "Diana Flores-Peregrina"
  site-url: https://www.dianafloresperegrina.com
  favicon: favicon.png
  page-footer:
    center: "© Diana Flores-Peregrina, 2026"

  navbar:
    left:
      - href: /
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: https://dianaefp.github.io/dianafpweb/CV_FloresPeregrina.pdf
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">